### PR TITLE
Fix pyspark requirements

### PR DESCRIPTION
**Pull request by zurk**
We have pyspark requirements from `sourced-engine` package: 
https://github.com/src-d/engine/blob/master/python/setup.py#L29

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Not so easy. Our cluster env uses 2.2.0 everywhere.

**Comment by zurk** [comment]
mmm. ok 
I try to find another solution.
Just FYI.
To install pyspark you need to specify version as is: `pyspark==2.2.0.post0`
but it installs as just `2.2.0` and after says that `pkg_resources.DistributionNotFound: The 'pyspark==2.2.0.post0' distribution was not found and is required by sourced-ml`... :/

**Comment by zurk** [comment]
now it works fine.

**Comment by vmarkovtsev** [comment]
@zurk No it's not

```
  Could not find a version that satisfies the requirement pyspark==2.2.0 (from -r requirements.txt (line 9)) (from versions: 2.1.2, 2.2.0.post0, 2.2.1)
No matching distribution found for pyspark==2.2.0 (from -r requirements.txt (line 9))
```

I guess we can close this.

**Pull request closed without merging**
