### PR TITLE
Add style check stage

### PR DESCRIPTION
**Pull request by zurk**
Add style check stage in Travis.
Also, harmonize style check with https://github.com/src-d/style-analyzer.

Better to review by commits.

### CODE REVIEW

**Comment by zurk** [comment]
wow, GitHub marks force-pushes now.

**Comment by vmarkovtsev** [comment]
Yep, did not see them last week...

@zurk Can you please make the single `.flake8` config the same way it works in the current `lookout-sdk-ml` or `style-analyzer`. BTW: damn, you've done much work!!

**Comment by zurk** [comment]
done.

**Comment by zurk** [comment]
rebased and fix `requirements.txt` conflict

**Comment by zurk** [comment]
Something bad happened in dependencies for Python 3.4. Maybe it is a good time to drop it, @vmarkovtsev?

**Comment by vmarkovtsev** [comment]
@zurk Let's return to this problem when we migrate to UASTv2 - the new client does not support 3.4.

This particular problem is because pip updated to version 19 and broke quite many things. We need to pin its version to 18.1 (or even older if the problem persisits). Here is how: https://github.com/src-d/hercules/blob/master/.travis.yml#L51

**Pull request merged**
