### PR TITLE
Update name to sourced.ml in README

### PR DESCRIPTION
**Pull request by marnovo**

### CODE REVIEW

**Comment by marnovo** [comment]
cc: @vmarkovtsev

**Comment by vmarkovtsev** [comment]
Sorry, I cannot accept this PR. The current master is ast2vec everywhere and we cannot rename it. Develop branch is already renamed though.

**Comment by marnovo** [comment]
There are no changes to the code, links to PyPi or commands, for not breaking anything. Purely aesthetic on the readme alone just to get rid of the old naming. Anyhow, feel free to reject and close it.

**Comment by vmarkovtsev** [comment]
OK, you mention the former name, so let's see how we confuse people.

**Pull request merged**
