### PR TITLE
Training pipeline for identifier splitter.

### PR DESCRIPTION
**Pull request by EgorBu**
* custom metrics to measure progress during the training
* model builders for CNN/RNN
* training pipeline
* data generators
* and many more

The format of saving the model should be fixed when  https://github.com/src-d/ml/pull/243 will be merged.

Signed-off-by: egor <egor@sourced.tech>

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@zurk @r0mainK Please help me with this monster.

Any split suggestions are welcome.

**Comment by zurk** [comment]
Should we agree about splitting and ask @EgorBu to split first?

**Comment by vmarkovtsev** [comment]
@EgorBu Could you please combine Konts's and Romain's suggestions and split this PR?

**Comment by EgorBu** [comment]
I will think what can be done and how to split it better because all parts are highly dependable on each other. Thank you for the feedback! I will give additional love to this PR)

**Comment by EgorBu** [comment]
Splitted into https://github.com/src-d/ml/pull/255, https://github.com/src-d/ml/pull/256, https://github.com/src-d/ml/pull/257

**Pull request closed without merging**
