### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by agarwalrounak**
ou --> you
occurances --> occurrences

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Thanks @agarwalrounak

@zurk Can you please fix the CI

**Comment by zurk** [comment]
ok, tomorrow.

**Comment by vmarkovtsev** [comment]
@zurk tomorrow comes today

**Comment by zurk** [comment]
@agarwalrounak, as soon as we merge https://github.com/src-d/ml/pull/339 you can rebase your PR and pass Travis checks. :tada:

**Comment by zurk** [comment]
PR is merged.
@agarwalrounak, please rebase your PR on top of current master.

**Comment by agarwalrounak** [comment]
Done!

**Comment by vmarkovtsev** [comment]
Thanks for bearing with us @agarwalrounak

**Comment by agarwalrounak** [comment]
My pleasure :smiley:

**Pull request merged**
