### PR TITLE
Update modelforge requirements

### PR DESCRIPTION
**Pull request by r0mainK**
all in title

### CODE REVIEW

**Comment by r0mainK** [comment]
@vmarkovtsev so tests are failing bc of changes in modelforge, I would need to modify modelforge a bit (basically move arg parsers out of the main ) to icorrect errors cleanly.
However, why do we have this dump in commands in the first place ? It does exactly the same as modelforge with less features, and modelforge is a requirement of ml. IMO we should take it out.

**Comment by vmarkovtsev** [comment]
Looks fair to remove.

**Comment by r0mainK** [comment]
@vmarkovtsev dump tests seem to be failing due to fkin dulwich: basically `git clone` fails. I added skip for the DumpTest with a TODO. Alternatively, since `dump` does not need the index if there is no backend, I could simply modify modelforge, so it's as you want.

**Comment by r0mainK** [comment]
@vmarkovtsev to be merged when you can

**Comment by vmarkovtsev** [comment]
@r0mainK Expecting a better `git clone` workaround/fix than `unittest.skip` :wink:

**Pull request merged**
