### PR TITLE
Delete NBOW model

### PR DESCRIPTION
**Pull request by zurk**
Signed-off-by: Konstantin Slavnov konstantin@sourced.tech

### CODE REVIEW

**Comment by zurk** [comment]
@vmarkovtsev We have id2vec model to store embeddings. I think to merge `BOWBase` and `BOW` model. What do you think about that?

**Comment by vmarkovtsev** [comment]
Good, because BOWBase was created to unify BOW and nBOW

**Comment by vmarkovtsev** [comment]
@zurk CI build failed - tests left?

**Comment by zurk** [comment]
yes. will fix.

**Pull request merged**
