### PR TITLE
Move ArgumentDefaultsHelpFormatterNoNone class 

### PR DESCRIPTION
**Pull request by r0mainK**
Moved ArgumentDefaultsHelpFormatterNoNone form __main__ to sourced/ml/cmd_entries/args.py and put it into sourced/ml/cmd_entries/__init__.py

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@r0mainK Please also mind the commit message format described in CONTRIBUTING.md

**Comment by r0mainK** [comment]
@vmarkovtsev Modified the commit message and the `__init__`(to put the import at the top, was that what you meant by PEP8 ? )

**Comment by vmarkovtsev** [comment]
Yep, pep8 check.

The commit message should be in the present tense https://github.com/src-d/ml/blob/master/CONTRIBUTING.md#format-of-the-commit-message

**Comment by r0mainK** [comment]
My bad, just renamed the commit message to  `Move class to cmd_entries/args.py`

**Pull request merged**
